"""empty message

Revision ID: 78a26ee74c97
Revises: ed657e16ce20
Create Date: 2017-05-29 11:17:54.688072

"""

# revision identifiers, used by Alembic.
revision = '78a26ee74c97'
down_revision = 'ed657e16ce20'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
